import Link from "next/link";
import { redirect } from "next/navigation";
import ProfileForm from "@/app/components/ProfileForm";
import { logout } from "@/app/account/actions";
import { createClient } from "@/lib/supabase/server";
import type { Profile } from "@/lib/types";
import { staffRoles } from "@/lib/types";
import { getLocale } from "@/lib/locale";
import { roleLabelsI18n } from "@/lib/i18n";
export default async function AccountPage(){const locale=await getLocale();const ro=locale==="ro";const supabase=await createClient();const {data:claimsData,error:claimsError}=await supabase.auth.getClaims();const userId=claimsData?.claims?.sub;if(claimsError||!userId)redirect("/login");const {data,error}=await supabase.from("profiles").select("*").eq("id",userId).single();if(error||!data)throw new Error("Profile not found");const profile=data as Profile;const isStaff=staffRoles.includes(profile.role);return <main className="accountPage"><section className="accountHero"><div className="container"><p className="eyebrow">{ro?"CONT PERSONAL":"ЛИЧНЫЙ КАБИНЕТ"}</p><h1>{profile.full_name||(ro?"Utilizator":"Пользователь")}</h1><div className="roleBadge">{roleLabelsI18n[locale][profile.role]}</div></div></section><section className="section"><div className="container accountGrid"><article className="accountPanel"><p className="eyebrow blue">{ro?"PROFIL":"ПРОФИЛЬ"}</p><h2>{ro?"Datele mele":"Мои данные"}</h2><div className="accountDetails"><div><span>Email</span><strong>{profile.email||"—"}</strong></div><div><span>{ro?"Rol":"Роль"}</span><strong>{roleLabelsI18n[locale][profile.role]}</strong></div></div><ProfileForm fullName={profile.full_name||""} locale={locale}/></article><aside className="accountSide">{isStaff?<div className="staffCallout"><p className="eyebrow">{ro?"ECHIPA CLUBULUI":"СОТРУДНИК КЛУБА"}</p><h3>{ro?"Acces la administrare":"Доступ к управлению"}</h3><p>{ro?"Rolul tău permite accesul la panoul de administrare FC Edineț.":"Твоя роль позволяет открыть служебную панель FC Edineț."}</p><Link className="primaryButton" href="/admin">{ro?"Deschide administrarea":"Открыть админку"}</Link></div>:<div className="fanCallout"><p className="eyebrow blue">{ro?"SUPORTER":"БОЛЕЛЬЩИК"}</p><h3>{ro?"Cont activ":"Аккаунт активен"}</h3><p>{ro?"În etapele următoare vor apărea comentarii, știri favorite și alte funcții pentru suporteri.":"На следующих этапах здесь появятся комментарии, избранные новости и другие возможности болельщика."}</p></div>}<form action={logout}><button className="logoutButton" type="submit">{ro?"Ieși din cont":"Выйти из аккаунта"}</button></form></aside></div></section></main>}
