-- FC EDINET v0.6
-- Категории новостей, публикации и публичный бакет обложек.
-- Запускать после предыдущих миграций проекта.

create table if not exists public.news_categories (
  id bigint generated by default as identity primary key,
  name text not null unique,
  slug text not null unique,
  display_order integer not null default 0,
  is_active boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.news (
  id bigint generated by default as identity primary key,
  category_id bigint references public.news_categories(id) on delete set null,
  title text not null,
  slug text not null unique,
  excerpt text,
  content text not null default '',
  cover_image_url text,
  author_name text,
  status text not null default 'draft',
  published_at timestamptz,
  views bigint not null default 0,
  is_featured boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint news_status_check check (status in ('draft', 'review', 'published'))
);

create index if not exists news_status_published_idx
  on public.news (status, published_at desc);
create index if not exists news_category_published_idx
  on public.news (category_id, published_at desc);
create index if not exists news_featured_published_idx
  on public.news (is_featured, published_at desc);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists set_news_updated_at on public.news;
create trigger set_news_updated_at
before update on public.news
for each row execute function public.set_updated_at();

-- Защищаем таблицы. Сейчас сайт имеет только публичное чтение.
alter table public.news_categories enable row level security;
alter table public.news enable row level security;

revoke all on table public.news_categories from anon, authenticated;
revoke all on table public.news from anon, authenticated;
grant select on table public.news_categories to anon, authenticated;
grant select on table public.news to anon, authenticated;

drop policy if exists "Public can read active news categories" on public.news_categories;
create policy "Public can read active news categories"
on public.news_categories
for select
to public
using (is_active = true);

drop policy if exists "Public can read published news" on public.news;
create policy "Public can read published news"
on public.news
for select
to public
using (
  status = 'published'
  and published_at is not null
  and published_at <= now()
);

-- Бакет обложек. Он публичный на чтение, но мы НЕ создаём public upload/update/delete policies.
-- Пока загрузка выполняется вручную через Supabase Dashboard.
insert into storage.buckets (
  id,
  name,
  public,
  file_size_limit,
  allowed_mime_types
)
values (
  'news',
  'news',
  true,
  8388608,
  array['image/jpeg', 'image/png', 'image/webp']
)
on conflict (id) do update
set
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

-- Стандартные категории.
insert into public.news_categories (name, slug, display_order)
values
  ('Матчи', 'matches', 10),
  ('Команда', 'team', 20),
  ('Интервью', 'interviews', 30),
  ('Клуб', 'club', 40),
  ('Трансферы', 'transfers', 50),
  ('Академия', 'academy', 60)
on conflict (slug) do update
set name = excluded.name,
    display_order = excluded.display_order,
    is_active = true;

-- Три демонстрационные опубликованные новости.
-- Их можно отредактировать или удалить после проверки.
insert into public.news (
  category_id, title, slug, excerpt, content, author_name,
  status, published_at, is_featured
)
values
(
  (select id from public.news_categories where slug = 'club'),
  'FC Edineț запускает обновлённый официальный сайт',
  'fc-edinet-zapuskaet-obnovlennyi-sait',
  'Клуб развивает собственную цифровую платформу для новостей, матчей, состава и медиаконтента.',
  $news$FC Edineț продолжает развивать коммуникацию с болельщиками и создаёт новое официальное цифровое пространство.

На сайте будут публиковаться клубные новости, информация о матчах, состав первой команды, фотографии, видео и материалы об истории клуба.

На следующих этапах появятся личные кабинеты пользователей, комментарии и собственная редакционная система для сотрудников клуба.$news$,
  'FC Edineț',
  'published',
  now() - interval '2 days',
  true
),
(
  (select id from public.news_categories where slug = 'team'),
  'Первая команда продолжает подготовку к сезону',
  'pervaya-komanda-prodolzhaet-podgotovku',
  'Игроки FC Edineț продолжают тренировочный процесс и подготовку к ближайшим официальным матчам.',
  $news$Первая команда FC Edineț продолжает подготовку к ближайшим матчам.

Тренировочный процесс включает работу с мячом, тактические упражнения и физическую подготовку.

Позже этот демонстрационный материал можно заменить реальной новостью клуба через административную систему.$news$,
  'FC Edineț',
  'published',
  now() - interval '1 day',
  false
),
(
  (select id from public.news_categories where slug = 'matches'),
  'В центре внимания — следующий матч FC Edineț',
  'v-centre-vnimaniya-sleduyushchii-match',
  'В разделе матчей вскоре появятся календарь, результаты и полноценные страницы игр.',
  $news$Матчевый раздел официального сайта станет одним из ключевых источников информации для болельщиков.

Здесь будут доступны предстоящие встречи, результаты, место проведения и связанные с матчем новости.

На отдельном этапе мы подключим этот блок к собственной таблице матчей в Supabase.$news$,
  'FC Edineț',
  'published',
  now() - interval '4 hours',
  false
)
on conflict (slug) do nothing;
