-- FC EDINET v1.0
-- Команды, турниры и матчи.
-- Запускать ПОСЛЕ 006_players_admin.sql.

create table if not exists public.competitions (
  id bigint generated by default as identity primary key,
  name text not null,
  slug text not null unique,
  season text,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.teams (
  id bigint generated by default as identity primary key,
  name text not null,
  short_name text,
  slug text not null unique,
  city text,
  logo_url text,
  is_club boolean not null default false,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.matches (
  id bigint generated by default as identity primary key,
  competition_id bigint
    constraint matches_competition_id_fkey
    references public.competitions(id) on delete set null,
  home_team_id bigint not null
    constraint matches_home_team_id_fkey
    references public.teams(id) on delete restrict,
  away_team_id bigint not null
    constraint matches_away_team_id_fkey
    references public.teams(id) on delete restrict,
  kickoff timestamptz not null,
  stadium text,
  round text,
  status text not null default 'scheduled'
    check (status in ('scheduled','live','finished','postponed','cancelled')),
  home_score integer check (home_score is null or home_score >= 0),
  away_score integer check (away_score is null or away_score >= 0),
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint matches_different_teams check (home_team_id <> away_team_id)
);

create index if not exists matches_kickoff_idx
  on public.matches (kickoff desc);

create index if not exists matches_status_kickoff_idx
  on public.matches (status, kickoff);

create or replace function public.set_generic_updated_at()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists competitions_set_updated_at on public.competitions;
create trigger competitions_set_updated_at
before update on public.competitions
for each row execute function public.set_generic_updated_at();

drop trigger if exists teams_set_updated_at on public.teams;
create trigger teams_set_updated_at
before update on public.teams
for each row execute function public.set_generic_updated_at();

drop trigger if exists matches_set_updated_at on public.matches;
create trigger matches_set_updated_at
before update on public.matches
for each row execute function public.set_generic_updated_at();

alter table public.competitions enable row level security;
alter table public.teams enable row level security;
alter table public.matches enable row level security;

grant select on table public.competitions, public.teams, public.matches
to anon, authenticated;

grant insert, update, delete on table public.competitions, public.teams, public.matches
to authenticated;

grant usage, select on sequence public.competitions_id_seq to authenticated;
grant usage, select on sequence public.teams_id_seq to authenticated;
grant usage, select on sequence public.matches_id_seq to authenticated;

-- Public read
drop policy if exists "Public can read active competitions" on public.competitions;
create policy "Public can read active competitions"
on public.competitions for select
to public
using (is_active = true);

drop policy if exists "Public can read active teams" on public.teams;
create policy "Public can read active teams"
on public.teams for select
to public
using (is_active = true);

drop policy if exists "Public can read matches" on public.matches;
create policy "Public can read matches"
on public.matches for select
to public
using (true);

-- Editor/Admin read all supporting records
drop policy if exists "Editors can read all competitions" on public.competitions;
create policy "Editors can read all competitions"
on public.competitions for select
to authenticated
using (public.is_editor_or_admin());

drop policy if exists "Editors can read all teams" on public.teams;
create policy "Editors can read all teams"
on public.teams for select
to authenticated
using (public.is_editor_or_admin());

-- Editor/Admin manage
drop policy if exists "Editors manage competitions" on public.competitions;
create policy "Editors manage competitions"
on public.competitions for all
to authenticated
using (public.is_editor_or_admin())
with check (public.is_editor_or_admin());

drop policy if exists "Editors manage teams" on public.teams;
create policy "Editors manage teams"
on public.teams for all
to authenticated
using (public.is_editor_or_admin())
with check (public.is_editor_or_admin());

drop policy if exists "Editors manage matches" on public.matches;
create policy "Editors manage matches"
on public.matches for all
to authenticated
using (public.is_editor_or_admin())
with check (public.is_editor_or_admin());

-- Базовые сущности проекта.
insert into public.competitions (name, slug, season, is_active)
values ('Liga 2', 'liga-2', '2026/27', true)
on conflict (slug) do update
set name = excluded.name,
    season = coalesce(public.competitions.season, excluded.season),
    is_active = true;

insert into public.teams (name, short_name, slug, city, is_club, is_active)
values ('FC Edineț', 'FC Edineț', 'fc-edinet', 'Edineț', true, true)
on conflict (slug) do update
set name = excluded.name,
    short_name = excluded.short_name,
    city = excluded.city,
    is_club = true,
    is_active = true;
