-- FC EDINET v1.2
-- Турнирная таблица.
-- Запускать ПОСЛЕ 010_team_home_stadium.sql.

create table if not exists public.standings (
  id bigint generated by default as identity primary key,
  competition_id bigint not null
    constraint standings_competition_id_fkey
    references public.competitions(id) on delete cascade,
  team_id bigint not null
    constraint standings_team_id_fkey
    references public.teams(id) on delete cascade,

  wins integer not null default 0 check (wins >= 0),
  draws integer not null default 0 check (draws >= 0),
  losses integer not null default 0 check (losses >= 0),
  goals_for integer not null default 0 check (goals_for >= 0),
  goals_against integer not null default 0 check (goals_against >= 0),

  -- Для штрафов/бонусов. Обычно 0.
  points_adjustment integer not null default 0,

  played integer generated always as
    (wins + draws + losses) stored,

  goal_difference integer generated always as
    (goals_for - goals_against) stored,

  points integer generated always as
    (wins * 3 + draws + points_adjustment) stored,

  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),

  constraint standings_competition_team_unique
    unique (competition_id, team_id)
);

create index if not exists standings_competition_sort_idx
  on public.standings (
    competition_id,
    points desc,
    goal_difference desc,
    goals_for desc
  );

drop trigger if exists standings_set_updated_at on public.standings;
create trigger standings_set_updated_at
before update on public.standings
for each row execute function public.set_generic_updated_at();

alter table public.standings enable row level security;

grant select on table public.standings to anon, authenticated;
grant insert, update, delete on table public.standings to authenticated;
grant usage, select on sequence public.standings_id_seq to authenticated;

drop policy if exists "Public can read standings" on public.standings;
create policy "Public can read standings"
on public.standings
for select
to public
using (true);

drop policy if exists "Editors manage standings" on public.standings;
create policy "Editors manage standings"
on public.standings
for all
to authenticated
using (public.is_editor_or_admin())
with check (public.is_editor_or_admin());
