-- FC EDINET v1.3
-- Публичный раздел клуба: профиль, стадион, руководство, достижения.
-- Запускать ПОСЛЕ 011_standings.sql.

create table if not exists public.club_profile (
  id smallint primary key default 1 check (id = 1),
  club_name text not null default 'FC Edineț',
  city text not null default 'Edineț',
  founded_year integer check (
    founded_year is null or founded_year between 1900 and 2100
  ),
  club_colors text,
  motto text,

  about_text text,
  history_text text,

  email text,
  phone text,
  address text,

  stadium_name text,
  stadium_capacity integer check (
    stadium_capacity is null or stadium_capacity >= 0
  ),
  stadium_address text,
  stadium_description text,

  hero_image_url text,
  stadium_image_url text,

  updated_at timestamptz not null default now()
);

insert into public.club_profile (
  id,
  club_name,
  city,
  club_colors,
  motto,
  stadium_name
)
values (
  1,
  'FC Edineț',
  'Edineț',
  'Синий / белый',
  'Вместе за Единец',
  'Stadionul Edineț'
)
on conflict (id) do nothing;

create table if not exists public.club_leadership (
  id bigint generated by default as identity primary key,
  name text not null,
  role text not null,
  bio text,
  photo_url text,
  display_order integer not null default 100,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.club_achievements (
  id bigint generated by default as identity primary key,
  year text,
  title text not null,
  description text,
  display_order integer not null default 100,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

drop trigger if exists club_profile_set_updated_at on public.club_profile;
create trigger club_profile_set_updated_at
before update on public.club_profile
for each row execute function public.set_generic_updated_at();

drop trigger if exists club_leadership_set_updated_at on public.club_leadership;
create trigger club_leadership_set_updated_at
before update on public.club_leadership
for each row execute function public.set_generic_updated_at();

drop trigger if exists club_achievements_set_updated_at on public.club_achievements;
create trigger club_achievements_set_updated_at
before update on public.club_achievements
for each row execute function public.set_generic_updated_at();

alter table public.club_profile enable row level security;
alter table public.club_leadership enable row level security;
alter table public.club_achievements enable row level security;

grant select on table
  public.club_profile,
  public.club_leadership,
  public.club_achievements
to anon, authenticated;

grant insert, update, delete on table
  public.club_profile,
  public.club_leadership,
  public.club_achievements
to authenticated;

grant usage, select on sequence public.club_leadership_id_seq to authenticated;
grant usage, select on sequence public.club_achievements_id_seq to authenticated;

drop policy if exists "Public can read club profile" on public.club_profile;
create policy "Public can read club profile"
on public.club_profile
for select
to public
using (true);

drop policy if exists "Editors manage club profile" on public.club_profile;
create policy "Editors manage club profile"
on public.club_profile
for all
to authenticated
using (public.is_editor_or_admin())
with check (public.is_editor_or_admin());

drop policy if exists "Public can read active leadership" on public.club_leadership;
create policy "Public can read active leadership"
on public.club_leadership
for select
to public
using (is_active = true);

drop policy if exists "Editors read all leadership" on public.club_leadership;
create policy "Editors read all leadership"
on public.club_leadership
for select
to authenticated
using (public.is_editor_or_admin());

drop policy if exists "Editors manage leadership" on public.club_leadership;
create policy "Editors manage leadership"
on public.club_leadership
for all
to authenticated
using (public.is_editor_or_admin())
with check (public.is_editor_or_admin());

drop policy if exists "Public can read active achievements" on public.club_achievements;
create policy "Public can read active achievements"
on public.club_achievements
for select
to public
using (is_active = true);

drop policy if exists "Editors read all achievements" on public.club_achievements;
create policy "Editors read all achievements"
on public.club_achievements
for select
to authenticated
using (public.is_editor_or_admin());

drop policy if exists "Editors manage achievements" on public.club_achievements;
create policy "Editors manage achievements"
on public.club_achievements
for all
to authenticated
using (public.is_editor_or_admin())
with check (public.is_editor_or_admin());

-- Storage for club/stadium/leadership images
insert into storage.buckets (
  id,
  name,
  public,
  file_size_limit,
  allowed_mime_types
)
values (
  'club',
  'club',
  true,
  8388608,
  array['image/jpeg', 'image/png', 'image/webp']
)
on conflict (id) do update
set
  name = excluded.name,
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

drop policy if exists "Public can view club images" on storage.objects;
create policy "Public can view club images"
on storage.objects
for select
to public
using (bucket_id = 'club');

drop policy if exists "Editors upload club images" on storage.objects;
create policy "Editors upload club images"
on storage.objects
for insert
to authenticated
with check (
  bucket_id = 'club'
  and public.is_editor_or_admin()
  and (storage.foldername(name))[1] = (select auth.uid())::text
  and lower(storage.extension(name)) in ('jpg','jpeg','png','webp')
);

drop policy if exists "Editors delete club images" on storage.objects;
create policy "Editors delete club images"
on storage.objects
for delete
to authenticated
using (
  bucket_id = 'club'
  and public.is_editor_or_admin()
);
