-- FC EDINET v1.4
-- Media Center: photo albums, photos, videos and public sharing.
-- Run AFTER 012_club_profile.sql.

create table if not exists public.media_albums (
  id bigint generated by default as identity primary key,
  title text not null,
  slug text not null unique,
  description text,
  event_date date,
  location text,
  cover_image_url text,
  is_published boolean not null default false,
  display_order integer not null default 100,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.media_photos (
  id bigint generated by default as identity primary key,
  album_id bigint not null
    constraint media_photos_album_id_fkey
    references public.media_albums(id) on delete cascade,
  image_url text not null,
  thumb_url text not null,
  storage_path text not null,
  thumb_storage_path text not null,
  original_name text,
  caption text,
  photographer text,
  display_order integer not null default 100,
  is_published boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.media_videos (
  id bigint generated by default as identity primary key,
  title text not null,
  description text,
  youtube_url text not null,
  youtube_id text not null,
  published_at date,
  is_published boolean not null default true,
  display_order integer not null default 100,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists media_albums_publish_idx
  on public.media_albums (is_published, event_date desc, created_at desc);

create index if not exists media_photos_album_idx
  on public.media_photos (album_id, is_published, display_order, id);

create index if not exists media_videos_publish_idx
  on public.media_videos (is_published, published_at desc, display_order);

drop trigger if exists media_albums_set_updated_at on public.media_albums;
create trigger media_albums_set_updated_at
before update on public.media_albums
for each row execute function public.set_generic_updated_at();

drop trigger if exists media_videos_set_updated_at on public.media_videos;
create trigger media_videos_set_updated_at
before update on public.media_videos
for each row execute function public.set_generic_updated_at();

alter table public.media_albums enable row level security;
alter table public.media_photos enable row level security;
alter table public.media_videos enable row level security;

grant select on table
  public.media_albums,
  public.media_photos,
  public.media_videos
to anon, authenticated;

grant insert, update, delete on table
  public.media_albums,
  public.media_photos,
  public.media_videos
to authenticated;

grant usage, select on sequence public.media_albums_id_seq to authenticated;
grant usage, select on sequence public.media_photos_id_seq to authenticated;
grant usage, select on sequence public.media_videos_id_seq to authenticated;

-- Public reads only published media.
drop policy if exists "Public can read published albums" on public.media_albums;
create policy "Public can read published albums"
on public.media_albums
for select
to public
using (is_published = true);

drop policy if exists "Editors can read all albums" on public.media_albums;
create policy "Editors can read all albums"
on public.media_albums
for select
to authenticated
using (public.is_editor_or_admin());

drop policy if exists "Editors manage albums" on public.media_albums;
create policy "Editors manage albums"
on public.media_albums
for all
to authenticated
using (public.is_editor_or_admin())
with check (public.is_editor_or_admin());

drop policy if exists "Public can read published photos" on public.media_photos;
create policy "Public can read published photos"
on public.media_photos
for select
to public
using (
  is_published = true
  and exists (
    select 1
    from public.media_albums a
    where a.id = album_id
      and a.is_published = true
  )
);

drop policy if exists "Editors can read all photos" on public.media_photos;
create policy "Editors can read all photos"
on public.media_photos
for select
to authenticated
using (public.is_editor_or_admin());

drop policy if exists "Editors manage photos" on public.media_photos;
create policy "Editors manage photos"
on public.media_photos
for all
to authenticated
using (public.is_editor_or_admin())
with check (public.is_editor_or_admin());

drop policy if exists "Public can read published videos" on public.media_videos;
create policy "Public can read published videos"
on public.media_videos
for select
to public
using (is_published = true);

drop policy if exists "Editors can read all videos" on public.media_videos;
create policy "Editors can read all videos"
on public.media_videos
for select
to authenticated
using (public.is_editor_or_admin());

drop policy if exists "Editors manage videos" on public.media_videos;
create policy "Editors manage videos"
on public.media_videos
for all
to authenticated
using (public.is_editor_or_admin())
with check (public.is_editor_or_admin());

-- Public media bucket.
insert into storage.buckets (
  id,
  name,
  public,
  file_size_limit,
  allowed_mime_types
)
values (
  'media',
  'media',
  true,
  12582912,
  array['image/jpeg','image/png','image/webp']
)
on conflict (id) do update
set
  name = excluded.name,
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

drop policy if exists "Public can view media files" on storage.objects;
create policy "Public can view media files"
on storage.objects
for select
to public
using (bucket_id = 'media');

drop policy if exists "Editors upload media files" on storage.objects;
create policy "Editors upload media files"
on storage.objects
for insert
to authenticated
with check (
  bucket_id = 'media'
  and public.is_editor_or_admin()
  and (storage.foldername(name))[1] = (select auth.uid())::text
  and lower(storage.extension(name)) in ('jpg','jpeg','png','webp')
);

drop policy if exists "Editors delete media files" on storage.objects;
create policy "Editors delete media files"
on storage.objects
for delete
to authenticated
using (
  bucket_id = 'media'
  and public.is_editor_or_admin()
);
