-- FC EDINET v1.7
-- Партнёры и спонсоры клуба.
-- Запускать ПОСЛЕ 016_audit_security.sql.

create table if not exists public.partners (
  id bigint generated by default as identity primary key,
  name text not null check (char_length(trim(name)) >= 2),
  slug text not null unique,
  website_url text,
  description text,
  logo_url text not null,
  logo_storage_path text,
  partner_level text not null default 'official'
    check (partner_level in ('main','official','technical','supporter')),
  display_order integer not null default 0 check (display_order >= 0),
  is_active boolean not null default true,
  show_on_homepage boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists partners_public_order_idx
  on public.partners (is_active, show_on_homepage, display_order, name);

create index if not exists partners_level_order_idx
  on public.partners (partner_level, display_order, name);

drop trigger if exists partners_set_updated_at on public.partners;
create trigger partners_set_updated_at
before update on public.partners
for each row execute function public.set_generic_updated_at();

alter table public.partners enable row level security;

grant select on table public.partners to anon, authenticated;
grant insert, update, delete on table public.partners to authenticated;

drop policy if exists "Public can read active partners" on public.partners;
create policy "Public can read active partners"
on public.partners
for select
to public
using (is_active = true);

drop policy if exists "Editors can read all partners" on public.partners;
create policy "Editors can read all partners"
on public.partners
for select
to authenticated
using (public.is_editor_or_admin());

drop policy if exists "Editors manage partners" on public.partners;
create policy "Editors manage partners"
on public.partners
for all
to authenticated
using (public.is_editor_or_admin())
with check (public.is_editor_or_admin());

insert into storage.buckets (
  id,
  name,
  public,
  file_size_limit,
  allowed_mime_types
)
values (
  'partners',
  'partners',
  true,
  5242880,
  array['image/jpeg','image/png','image/webp','image/svg+xml']
)
on conflict (id) do update
set
  name = excluded.name,
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

drop policy if exists "Public can view partner logos" on storage.objects;
create policy "Public can view partner logos"
on storage.objects
for select
to public
using (bucket_id = 'partners');

drop policy if exists "Editors upload partner logos" on storage.objects;
create policy "Editors upload partner logos"
on storage.objects
for insert
to authenticated
with check (
  bucket_id = 'partners'
  and public.is_editor_or_admin()
  and (storage.foldername(name))[1] = (select auth.uid())::text
  and lower(storage.extension(name)) in ('jpg','jpeg','png','webp','svg')
);

drop policy if exists "Editors update partner logos" on storage.objects;
create policy "Editors update partner logos"
on storage.objects
for update
to authenticated
using (
  bucket_id = 'partners'
  and public.is_editor_or_admin()
)
with check (
  bucket_id = 'partners'
  and public.is_editor_or_admin()
);

drop policy if exists "Editors delete partner logos" on storage.objects;
create policy "Editors delete partner logos"
on storage.objects
for delete
to authenticated
using (
  bucket_id = 'partners'
  and public.is_editor_or_admin()
);

-- Подключаем новый раздел к журналу v1.6.2.
drop trigger if exists partners_audit_trigger on public.partners;
create trigger partners_audit_trigger
after insert or update or delete on public.partners
for each row execute function public.write_audit_log();
