-- FC EDINET v2.1
-- Комментарии к новостям, жалобы, модерация/блокировки и журнал диагностики RU -> RO.
-- Запускать ПОСЛЕ 021_fan_account.sql.

-- ============================================================
-- 1. Комментарии к опубликованным новостям.
-- ============================================================
create table if not exists public.comments (
  id bigint generated by default as identity primary key,
  news_id bigint not null,
  user_id uuid not null,
  body text not null,
  status text not null default 'visible',
  author_display_name text not null default 'Болельщик',
  author_avatar_url text,
  moderated_by uuid,
  moderated_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint comments_news_id_fkey
    foreign key (news_id) references public.news(id) on delete cascade,
  constraint comments_user_id_fkey
    foreign key (user_id) references public.profiles(id) on delete cascade,
  constraint comments_moderated_by_fkey
    foreign key (moderated_by) references public.profiles(id) on delete set null,
  constraint comments_body_length_check
    check (char_length(trim(body)) between 1 and 2000),
  constraint comments_status_check
    check (status in ('visible','hidden'))
);

create index if not exists comments_news_status_created_idx
  on public.comments (news_id, status, created_at desc);
create index if not exists comments_user_created_idx
  on public.comments (user_id, created_at desc);
create index if not exists comments_moderated_by_idx
  on public.comments (moderated_by);

-- Имя/аватар комментария всегда берём из реального профиля, а не из формы клиента.
create or replace function public.hydrate_comment_author()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_name text;
  v_avatar text;
begin
  select
    coalesce(nullif(trim(p.display_name), ''), nullif(trim(p.full_name), ''), 'Болельщик'),
    p.avatar_url
  into v_name, v_avatar
  from public.profiles p
  where p.id = new.user_id;

  new.author_display_name := coalesce(v_name, 'Болельщик');
  new.author_avatar_url := v_avatar;
  return new;
end;
$$;

revoke all on function public.hydrate_comment_author() from public, anon, authenticated;

drop trigger if exists hydrate_comment_author on public.comments;
create trigger hydrate_comment_author
before insert on public.comments
for each row execute function public.hydrate_comment_author();

-- Небольшой серверный rate-limit: один комментарий от пользователя раз в 20 секунд.
-- Триггер SECURITY DEFINER нужен, чтобы проверка не зависела от клиентских RLS-прав.
create or replace function public.enforce_comment_rate_limit()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  if exists (
    select 1
    from public.comments c
    where c.user_id = new.user_id
      and c.created_at > now() - interval '20 seconds'
  ) then
    raise exception 'comment_rate_limit';
  end if;
  return new;
end;
$$;

revoke all on function public.enforce_comment_rate_limit() from public, anon, authenticated;

drop trigger if exists enforce_comment_rate_limit on public.comments;
create trigger enforce_comment_rate_limit
before insert on public.comments
for each row execute function public.enforce_comment_rate_limit();

-- Если пользователь поменял отображаемое имя/аватар, обновляем его старые комментарии.
create or replace function public.sync_comment_author_profile()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  if old.display_name is distinct from new.display_name
     or old.full_name is distinct from new.full_name
     or old.avatar_url is distinct from new.avatar_url then
    update public.comments
    set
      author_display_name = coalesce(nullif(trim(new.display_name), ''), nullif(trim(new.full_name), ''), 'Болельщик'),
      author_avatar_url = new.avatar_url,
      updated_at = now()
    where user_id = new.id;
  end if;
  return new;
end;
$$;

revoke all on function public.sync_comment_author_profile() from public, anon, authenticated;

drop trigger if exists sync_comment_author_profile on public.profiles;
create trigger sync_comment_author_profile
after update of display_name, full_name, avatar_url on public.profiles
for each row execute function public.sync_comment_author_profile();

-- ============================================================
-- 2. Блокировки возможности комментировать.
-- ============================================================
create table if not exists public.comment_blocks (
  user_id uuid primary key,
  reason text,
  blocked_until timestamptz,
  blocked_by uuid not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint comment_blocks_user_id_fkey
    foreign key (user_id) references public.profiles(id) on delete cascade,
  constraint comment_blocks_blocked_by_fkey
    foreign key (blocked_by) references public.profiles(id) on delete cascade,
  constraint comment_blocks_reason_length_check
    check (reason is null or char_length(reason) <= 500)
);

create index if not exists comment_blocks_until_idx
  on public.comment_blocks (blocked_until);
create index if not exists comment_blocks_blocked_by_idx
  on public.comment_blocks (blocked_by);

drop trigger if exists comment_blocks_set_updated_at on public.comment_blocks;
create trigger comment_blocks_set_updated_at
before update on public.comment_blocks
for each row execute function public.set_updated_at();

-- ============================================================
-- 3. Жалобы на комментарии.
-- ============================================================
create table if not exists public.comment_reports (
  id bigint generated by default as identity primary key,
  comment_id bigint not null,
  reporter_id uuid not null,
  reason text not null,
  details text,
  status text not null default 'pending',
  reviewed_by uuid,
  reviewed_at timestamptz,
  created_at timestamptz not null default now(),
  constraint comment_reports_comment_id_fkey
    foreign key (comment_id) references public.comments(id) on delete cascade,
  constraint comment_reports_reporter_id_fkey
    foreign key (reporter_id) references public.profiles(id) on delete cascade,
  constraint comment_reports_reviewed_by_fkey
    foreign key (reviewed_by) references public.profiles(id) on delete set null,
  constraint comment_reports_unique_reporter unique (comment_id, reporter_id),
  constraint comment_reports_reason_check
    check (reason in ('spam','offensive','harassment','other')),
  constraint comment_reports_details_length_check
    check (details is null or char_length(details) <= 500),
  constraint comment_reports_status_check
    check (status in ('pending','resolved','dismissed'))
);

create index if not exists comment_reports_status_created_idx
  on public.comment_reports (status, created_at desc);
create index if not exists comment_reports_comment_idx
  on public.comment_reports (comment_id, created_at desc);
create index if not exists comment_reports_reporter_idx
  on public.comment_reports (reporter_id);
create index if not exists comment_reports_reviewed_by_idx
  on public.comment_reports (reviewed_by);

-- ============================================================
-- 4. Диагностика автоперевода OpenAI.
-- ============================================================
create table if not exists public.translation_diagnostics (
  id bigint generated by default as identity primary key,
  actor_user_id uuid,
  content_type text not null,
  content_id text,
  content_label text,
  status text not null,
  model text not null,
  http_status integer,
  error_type text,
  error_code text,
  error_message text,
  request_id text,
  created_at timestamptz not null default now(),
  constraint translation_diagnostics_actor_user_id_fkey
    foreign key (actor_user_id) references public.profiles(id) on delete set null,
  constraint translation_diagnostics_status_check
    check (status in ('success','error'))
);

create index if not exists translation_diagnostics_created_idx
  on public.translation_diagnostics (created_at desc);
create index if not exists translation_diagnostics_status_created_idx
  on public.translation_diagnostics (status, created_at desc);
create index if not exists translation_diagnostics_actor_idx
  on public.translation_diagnostics (actor_user_id);

-- ============================================================
-- 5. RLS и технические права.
-- ============================================================
alter table public.comments enable row level security;
alter table public.comment_blocks enable row level security;
alter table public.comment_reports enable row level security;
alter table public.translation_diagnostics enable row level security;

revoke all on table public.comments from public, anon, authenticated;
revoke all on table public.comment_blocks from public, anon, authenticated;
revoke all on table public.comment_reports from public, anon, authenticated;
revoke all on table public.translation_diagnostics from public, anon, authenticated;

-- Комментарии: гостям только безопасные публичные поля.
grant select (id, news_id, body, status, author_display_name, author_avatar_url, created_at, updated_at)
  on table public.comments to anon;
grant select, insert, update, delete on table public.comments to authenticated;
grant usage, select on sequence public.comments_id_seq to authenticated;

-- Гость читает только видимые комментарии у реально опубликованных новостей.
drop policy if exists "Guests can read visible comments" on public.comments;
create policy "Guests can read visible comments"
on public.comments
for select
to anon
using (
  status = 'visible'
  and exists (
    select 1 from public.news n
    where n.id = news_id
      and n.status = 'published'
      and n.published_at is not null
      and n.published_at <= now()
  )
);

-- Авторизованный пользователь читает публичные комментарии, свои скрытые и все комментарии как editor/admin.
drop policy if exists "Authenticated can read allowed comments" on public.comments;
create policy "Authenticated can read allowed comments"
on public.comments
for select
to authenticated
using (
  (
    status = 'visible'
    and exists (
      select 1 from public.news n
      where n.id = news_id
        and n.status = 'published'
        and n.published_at is not null
        and n.published_at <= now()
    )
  )
  or user_id = (select auth.uid())
  or public.is_editor_or_admin()
);

-- Блокировки доступны самому пользователю (только чтение) и модераторам.
grant select, insert, update, delete on table public.comment_blocks to authenticated;

drop policy if exists "Users and moderators read comment blocks" on public.comment_blocks;
create policy "Users and moderators read comment blocks"
on public.comment_blocks
for select
to authenticated
using (user_id = (select auth.uid()) or public.is_editor_or_admin());

drop policy if exists "Editors insert comment blocks" on public.comment_blocks;
create policy "Editors insert comment blocks"
on public.comment_blocks
for insert
to authenticated
with check (public.is_editor_or_admin() and blocked_by = (select auth.uid()));

drop policy if exists "Editors update comment blocks" on public.comment_blocks;
create policy "Editors update comment blocks"
on public.comment_blocks
for update
to authenticated
using (public.is_editor_or_admin())
with check (public.is_editor_or_admin() and blocked_by = (select auth.uid()));

drop policy if exists "Editors delete comment blocks" on public.comment_blocks;
create policy "Editors delete comment blocks"
on public.comment_blocks
for delete
to authenticated
using (public.is_editor_or_admin());

-- Новый комментарий: только к опубликованной новости, только от себя, не чаще 1 раза в 20 секунд и без активной блокировки.
drop policy if exists "Users create own comments" on public.comments;
create policy "Users create own comments"
on public.comments
for insert
to authenticated
with check (
  user_id = (select auth.uid())
  and status = 'visible'
  and moderated_by is null
  and moderated_at is null
  and exists (
    select 1 from public.news n
    where n.id = news_id
      and n.status = 'published'
      and n.published_at is not null
      and n.published_at <= now()
  )
  and not exists (
    select 1 from public.comment_blocks b
    where b.user_id = (select auth.uid())
      and (b.blocked_until is null or b.blocked_until > now())
  )
);

-- Обычный пользователь может только удалить собственный комментарий.
drop policy if exists "Users delete own comments" on public.comments;
create policy "Users delete own comments"
on public.comments
for delete
to authenticated
using (user_id = (select auth.uid()));

-- Editor/admin может скрывать и восстанавливать комментарии.
drop policy if exists "Editors moderate comments" on public.comments;
create policy "Editors moderate comments"
on public.comments
for update
to authenticated
using (public.is_editor_or_admin())
with check (public.is_editor_or_admin());

-- Жалобы.
grant select, insert, update on table public.comment_reports to authenticated;
grant usage, select on sequence public.comment_reports_id_seq to authenticated;

drop policy if exists "Users and moderators read reports" on public.comment_reports;
create policy "Users and moderators read reports"
on public.comment_reports
for select
to authenticated
using (reporter_id = (select auth.uid()) or public.is_editor_or_admin());

drop policy if exists "Users report visible comments" on public.comment_reports;
create policy "Users report visible comments"
on public.comment_reports
for insert
to authenticated
with check (
  reporter_id = (select auth.uid())
  and status = 'pending'
  and reviewed_by is null
  and reviewed_at is null
  and exists (
    select 1 from public.comments c
    where c.id = comment_id
      and c.status = 'visible'
      and c.user_id <> (select auth.uid())
  )
);

drop policy if exists "Editors review reports" on public.comment_reports;
create policy "Editors review reports"
on public.comment_reports
for update
to authenticated
using (public.is_editor_or_admin())
with check (public.is_editor_or_admin());

-- Диагностика перевода — только editor/admin.
grant select, insert on table public.translation_diagnostics to authenticated;
grant usage, select on sequence public.translation_diagnostics_id_seq to authenticated;

drop policy if exists "Editors read translation diagnostics" on public.translation_diagnostics;
create policy "Editors read translation diagnostics"
on public.translation_diagnostics
for select
to authenticated
using (public.is_editor_or_admin());

drop policy if exists "Editors insert translation diagnostics" on public.translation_diagnostics;
create policy "Editors insert translation diagnostics"
on public.translation_diagnostics
for insert
to authenticated
with check (
  public.is_editor_or_admin()
  and actor_user_id = (select auth.uid())
);

-- ============================================================
-- 6. Аудит только административных объектов модерации.
-- Пользовательские комментарии/жалобы не пишем в общий audit_log, чтобы не засорять CMS-журнал.
-- ============================================================
drop trigger if exists audit_log_comment_blocks on public.comment_blocks;
create trigger audit_log_comment_blocks
after insert or update or delete on public.comment_blocks
for each row execute function public.write_audit_log();
