-- FC EDINET v2.1.2
-- Site-wide Visual Editor for public section heroes and dynamic page templates.
-- Run AFTER 023_visual_page_editor.sql.

create table if not exists public.site_page_designs (
  page_key text primary key check (page_key in (
    'news','team','matches','standings','club','media','partners',
    'template_news','template_player','template_album'
  )),
  slug text generated always as (page_key) stored,
  background_mode text not null default 'default' check (background_mode in ('default','custom','content')),
  desktop_image_url text,
  mobile_image_url text,
  desktop_position_x integer not null default 50 check (desktop_position_x between 0 and 100),
  desktop_position_y integer not null default 50 check (desktop_position_y between 0 and 100),
  desktop_zoom_percent integer not null default 100 check (desktop_zoom_percent between 100 and 240),
  mobile_position_x integer not null default 50 check (mobile_position_x between 0 and 100),
  mobile_position_y integer not null default 50 check (mobile_position_y between 0 and 100),
  mobile_zoom_percent integer not null default 100 check (mobile_zoom_percent between 100 and 300),
  hero_height_desktop integer not null default 310 check (hero_height_desktop between 200 and 950),
  hero_height_mobile integer not null default 250 check (hero_height_mobile between 180 and 900),
  overlay_opacity integer not null default 58 check (overlay_opacity between 0 and 95),
  overlay_style text not null default 'solid' check (overlay_style in ('solid','gradient-left','gradient-right')),
  text_alignment text not null default 'left' check (text_alignment in ('left','center','right')),
  content_width integer not null default 720 check (content_width between 420 and 1200),
  show_eyebrow boolean not null default true,
  show_description boolean not null default true,
  eyebrow_ru text,
  eyebrow_ro text,
  title_ru text,
  title_ro text,
  description_ru text,
  description_ro text,
  updated_by uuid references auth.users(id) on delete set null,
  updated_at timestamptz not null default now()
);

create table if not exists public.site_page_design_drafts (
  page_key text primary key check (page_key in (
    'news','team','matches','standings','club','media','partners',
    'template_news','template_player','template_album'
  )),
  background_mode text not null default 'default' check (background_mode in ('default','custom','content')),
  desktop_image_url text,
  mobile_image_url text,
  desktop_position_x integer not null default 50 check (desktop_position_x between 0 and 100),
  desktop_position_y integer not null default 50 check (desktop_position_y between 0 and 100),
  desktop_zoom_percent integer not null default 100 check (desktop_zoom_percent between 100 and 240),
  mobile_position_x integer not null default 50 check (mobile_position_x between 0 and 100),
  mobile_position_y integer not null default 50 check (mobile_position_y between 0 and 100),
  mobile_zoom_percent integer not null default 100 check (mobile_zoom_percent between 100 and 300),
  hero_height_desktop integer not null default 310 check (hero_height_desktop between 200 and 950),
  hero_height_mobile integer not null default 250 check (hero_height_mobile between 180 and 900),
  overlay_opacity integer not null default 58 check (overlay_opacity between 0 and 95),
  overlay_style text not null default 'solid' check (overlay_style in ('solid','gradient-left','gradient-right')),
  text_alignment text not null default 'left' check (text_alignment in ('left','center','right')),
  content_width integer not null default 720 check (content_width between 420 and 1200),
  show_eyebrow boolean not null default true,
  show_description boolean not null default true,
  eyebrow_ru text,
  eyebrow_ro text,
  title_ru text,
  title_ro text,
  description_ru text,
  description_ro text,
  updated_by uuid references auth.users(id) on delete set null,
  updated_at timestamptz not null default now()
);

create table if not exists public.site_page_design_versions (
  id bigint generated by default as identity primary key,
  page_key text not null check (page_key in (
    'news','team','matches','standings','club','media','partners',
    'template_news','template_player','template_album'
  )),
  label text,
  snapshot jsonb not null,
  published_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now()
);

insert into public.site_page_designs (
  page_key, background_mode, hero_height_desktop, hero_height_mobile,
  overlay_opacity, overlay_style, content_width
)
values
  ('news','default',310,250,58,'solid',720),
  ('team','default',310,250,58,'solid',720),
  ('matches','default',310,250,58,'solid',720),
  ('standings','default',310,250,58,'solid',720),
  ('club','content',430,350,70,'gradient-left',1050),
  ('media','default',330,270,58,'solid',720),
  ('partners','default',310,250,58,'solid',720),
  ('template_news','default',360,310,58,'solid',980),
  ('template_player','default',660,760,58,'solid',1200),
  ('template_album','content',390,340,68,'gradient-left',1000)
on conflict (page_key) do nothing;

create index if not exists site_page_designs_updated_by_idx
  on public.site_page_designs (updated_by);
create index if not exists site_page_design_drafts_updated_by_idx
  on public.site_page_design_drafts (updated_by);
create index if not exists site_page_design_versions_page_created_idx
  on public.site_page_design_versions (page_key, created_at desc);
create index if not exists site_page_design_versions_published_by_idx
  on public.site_page_design_versions (published_by, created_at desc);

alter table public.site_page_designs enable row level security;
alter table public.site_page_design_drafts enable row level security;
alter table public.site_page_design_versions enable row level security;

grant select on table public.site_page_designs to anon, authenticated;
grant insert, update, delete on table public.site_page_designs to authenticated;
grant select, insert, update, delete on table public.site_page_design_drafts to authenticated;
grant select, insert on table public.site_page_design_versions to authenticated;
grant usage, select on sequence public.site_page_design_versions_id_seq to authenticated;

drop policy if exists "Public read site page designs" on public.site_page_designs;
create policy "Public read site page designs"
on public.site_page_designs for select to anon, authenticated using (true);

drop policy if exists "Editors insert site page designs" on public.site_page_designs;
create policy "Editors insert site page designs"
on public.site_page_designs for insert to authenticated with check (public.is_editor_or_admin());

drop policy if exists "Editors update site page designs" on public.site_page_designs;
create policy "Editors update site page designs"
on public.site_page_designs for update to authenticated using (public.is_editor_or_admin()) with check (public.is_editor_or_admin());

drop policy if exists "Editors delete site page designs" on public.site_page_designs;
create policy "Editors delete site page designs"
on public.site_page_designs for delete to authenticated using (public.is_editor_or_admin());

drop policy if exists "Editors manage site page design drafts" on public.site_page_design_drafts;
create policy "Editors manage site page design drafts"
on public.site_page_design_drafts for all to authenticated
using (public.is_editor_or_admin()) with check (public.is_editor_or_admin());

drop policy if exists "Editors read site page design versions" on public.site_page_design_versions;
create policy "Editors read site page design versions"
on public.site_page_design_versions for select to authenticated
using (public.is_editor_or_admin());

drop policy if exists "Editors create site page design versions" on public.site_page_design_versions;
create policy "Editors create site page design versions"
on public.site_page_design_versions for insert to authenticated
with check (public.is_editor_or_admin());

-- Published design changes are part of the existing audit log.
drop trigger if exists audit_log_site_page_designs on public.site_page_designs;
create trigger audit_log_site_page_designs
after insert or update or delete on public.site_page_designs
for each row execute function public.write_audit_log();
