-- FC EDINEȚ v2.1.8 — Global Header + Footer Builder

create table if not exists public.site_global_designs (
  component_key text primary key check (component_key in ('header','footer')),
  config jsonb not null default '{}'::jsonb,
  updated_by uuid references auth.users(id) on delete set null,
  updated_at timestamptz not null default now()
);

create table if not exists public.site_global_design_drafts (
  component_key text primary key check (component_key in ('header','footer')),
  config jsonb not null default '{}'::jsonb,
  updated_by uuid references auth.users(id) on delete set null,
  updated_at timestamptz not null default now()
);

create table if not exists public.site_global_design_versions (
  id bigint generated by default as identity primary key,
  component_key text not null check (component_key in ('header','footer')),
  label text,
  snapshot jsonb not null,
  published_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now()
);

create index if not exists site_global_design_versions_component_created_idx on public.site_global_design_versions(component_key, created_at desc);
create index if not exists site_global_designs_updated_by_idx on public.site_global_designs(updated_by);
create index if not exists site_global_drafts_updated_by_idx on public.site_global_design_drafts(updated_by);
create index if not exists site_global_versions_published_by_idx on public.site_global_design_versions(published_by);

insert into public.site_global_designs(component_key, config)
values
('header', '{
  "topbar_enabled": true,
  "topbar_text_ru": "Официальный сайт FC Edineț",
  "topbar_text_ro": "Site-ul oficial FC Edineț",
  "sticky": true,
  "background": "glass",
  "height_desktop": 78,
  "height_mobile": 68,
  "logo_mode": "crest",
  "logo_url": null,
  "logo_width": 46,
  "brand_name": "FC EDINEȚ",
  "brand_subtitle": "MOLDOVA",
  "show_brand_text": true,
  "show_language": true,
  "show_search": true,
  "show_account": true,
  "show_admin_link": true,
  "nav_order": ["news","team","matches","standings","club","media"],
  "nav_visibility": {"news":true,"team":true,"matches":true,"standings":true,"club":true,"media":true}
}'::jsonb),
('footer', '{
  "background": "dark",
  "logo_mode": "crest",
  "logo_url": null,
  "logo_width": 46,
  "brand_name": "FC EDINEȚ",
  "brand_subtitle": "MOLDOVA",
  "about_ru": "Официальный сайт футбольного клуба FC Edineț.",
  "about_ro": "Site-ul oficial al clubului de fotbal FC Edineț.",
  "show_about": true,
  "columns": [
    {"id":"club","title_ru":"Клуб","title_ro":"Club","visible":true,"links":[{"id":"history","label_ru":"История","label_ro":"Istorie","href":"/club"},{"id":"stadium","label_ru":"Стадион","label_ro":"Stadion","href":"/club"},{"id":"partners","label_ru":"Партнёры","label_ro":"Parteneri","href":"/partners"}]},
    {"id":"team","title_ru":"Команда","title_ro":"Echipa","visible":true,"links":[{"id":"players","label_ru":"Игроки","label_ro":"Jucători","href":"/team"},{"id":"matches","label_ru":"Матчи","label_ro":"Meciuri","href":"/matches"}]},
    {"id":"media","title_ru":"Медиа","title_ro":"Media","visible":true,"links":[{"id":"news","label_ru":"Новости","label_ro":"Știri","href":"/news"},{"id":"photos","label_ru":"Фото","label_ro":"Foto","href":"/media"},{"id":"videos","label_ru":"Видео","label_ro":"Video","href":"/media"}]}
  ],
  "social_enabled": false,
  "facebook_url": "",
  "instagram_url": "",
  "youtube_url": "",
  "tiktok_url": "",
  "show_copyright": true,
  "copyright_text": "© 2026 FC Edineț",
  "show_version": true,
  "padding_top": 60,
  "padding_bottom": 26
}'::jsonb)
on conflict (component_key) do nothing;

alter table public.site_global_designs enable row level security;
alter table public.site_global_design_drafts enable row level security;
alter table public.site_global_design_versions enable row level security;

-- Published config is public.
drop policy if exists "Public can read global designs" on public.site_global_designs;
create policy "Public can read global designs" on public.site_global_designs for select to anon, authenticated using (true);
drop policy if exists "Editors can insert global designs" on public.site_global_designs;
create policy "Editors can insert global designs" on public.site_global_designs for insert to authenticated with check (public.is_editor_or_admin());
drop policy if exists "Editors can update global designs" on public.site_global_designs;
create policy "Editors can update global designs" on public.site_global_designs for update to authenticated using (public.is_editor_or_admin()) with check (public.is_editor_or_admin());

-- Drafts never have a public read policy.
drop policy if exists "Editors can read global drafts" on public.site_global_design_drafts;
create policy "Editors can read global drafts" on public.site_global_design_drafts for select to authenticated using (public.is_editor_or_admin());
drop policy if exists "Editors can insert global drafts" on public.site_global_design_drafts;
create policy "Editors can insert global drafts" on public.site_global_design_drafts for insert to authenticated with check (public.is_editor_or_admin());
drop policy if exists "Editors can update global drafts" on public.site_global_design_drafts;
create policy "Editors can update global drafts" on public.site_global_design_drafts for update to authenticated using (public.is_editor_or_admin()) with check (public.is_editor_or_admin());
drop policy if exists "Editors can delete global drafts" on public.site_global_design_drafts;
create policy "Editors can delete global drafts" on public.site_global_design_drafts for delete to authenticated using (public.is_editor_or_admin());

-- Version history is staff-only.
drop policy if exists "Editors can read global versions" on public.site_global_design_versions;
create policy "Editors can read global versions" on public.site_global_design_versions for select to authenticated using (public.is_editor_or_admin());
drop policy if exists "Editors can insert global versions" on public.site_global_design_versions;
create policy "Editors can insert global versions" on public.site_global_design_versions for insert to authenticated with check (public.is_editor_or_admin());
drop policy if exists "Admins can delete global versions" on public.site_global_design_versions;
create policy "Admins can delete global versions" on public.site_global_design_versions for delete to authenticated using (public.current_user_role() = 'admin');

grant select on public.site_global_designs to anon, authenticated;
grant insert, update on public.site_global_designs to authenticated;
grant select, insert, update, delete on public.site_global_design_drafts to authenticated;
grant select, insert, delete on public.site_global_design_versions to authenticated;

drop trigger if exists set_site_global_designs_updated_at on public.site_global_designs;
create trigger set_site_global_designs_updated_at before update on public.site_global_designs for each row execute function public.set_updated_at();
drop trigger if exists set_site_global_drafts_updated_at on public.site_global_design_drafts;
create trigger set_site_global_drafts_updated_at before update on public.site_global_design_drafts for each row execute function public.set_updated_at();

drop trigger if exists audit_log_site_global_designs on public.site_global_designs;
create trigger audit_log_site_global_designs after insert or update or delete on public.site_global_designs for each row execute function public.write_audit_log();
