-- FC EDINEȚ v2.2.0.1 — Player statistics foundation (UUID player_id fix)
-- Run AFTER 033_visual_editor_final_audit.sql.
-- Adds seasons, competition-to-season mapping, per-match player statistics,
-- match statistics workflow state and a season aggregation view.

create table if not exists public.seasons (
  id bigint generated by default as identity primary key,
  name text not null unique,
  slug text not null unique,
  starts_on date,
  ends_on date,
  is_current boolean not null default false,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint seasons_dates_check check (
    starts_on is null or ends_on is null or starts_on <= ends_on
  )
);

-- Preserve seasons already typed into competitions.season.
insert into public.seasons (name, slug, is_current, is_active)
select distinct
  btrim(c.season),
  lower(regexp_replace(btrim(c.season), '[^a-zA-Z0-9]+', '-', 'g')) || '-' || substr(md5(btrim(c.season)), 1, 6),
  false,
  true
from public.competitions c
where c.season is not null and btrim(c.season) <> ''
on conflict do nothing;

-- Current project season. This is idempotent and only fills missing dates/current flag.
insert into public.seasons (
  name, slug, starts_on, ends_on, is_current, is_active
)
values (
  '2026/27', '2026-27', date '2026-07-01', date '2027-06-30', true, true
)
on conflict (name) do update
set
  starts_on = coalesce(public.seasons.starts_on, excluded.starts_on),
  ends_on = coalesce(public.seasons.ends_on, excluded.ends_on),
  is_active = true;

-- Exactly one current season. If 2026/27 exists, make it current.
update public.seasons set is_current = (name = '2026/27');

create unique index if not exists seasons_one_current_idx
  on public.seasons ((is_current))
  where is_current = true;

alter table public.competitions
  add column if not exists season_id bigint;

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'competitions_season_id_fkey'
  ) then
    alter table public.competitions
      add constraint competitions_season_id_fkey
      foreign key (season_id)
      references public.seasons(id)
      on delete set null;
  end if;
end $$;

update public.competitions c
set season_id = s.id
from public.seasons s
where c.season_id is null
  and c.season is not null
  and btrim(c.season) = s.name;

update public.competitions c
set season_id = s.id
from public.seasons s
where c.season_id is null
  and s.is_current = true;

create index if not exists competitions_season_id_idx
  on public.competitions (season_id, is_active);

create table if not exists public.player_match_stats (
  id bigint generated by default as identity primary key,
  match_id bigint not null
    references public.matches(id) on delete cascade,
  player_id uuid not null
    references public.players(id) on delete cascade,
  competition_id bigint
    references public.competitions(id) on delete set null,
  season_id bigint
    references public.seasons(id) on delete set null,
  team_id bigint
    references public.teams(id) on delete set null,

  appearance text not null default 'starter'
    check (appearance in ('starter', 'substitute')),
  position text
    check (
      position is null
      or position in ('goalkeeper', 'defender', 'midfielder', 'forward')
    ),
  is_captain boolean not null default false,
  minutes_played smallint not null default 0
    check (minutes_played between 0 and 130),

  goals smallint not null default 0 check (goals between 0 and 20),
  assists smallint not null default 0 check (assists between 0 and 20),
  own_goals smallint not null default 0 check (own_goals between 0 and 10),
  penalties_scored smallint not null default 0 check (penalties_scored between 0 and 20),
  penalties_missed smallint not null default 0 check (penalties_missed between 0 and 20),
  yellow_cards smallint not null default 0 check (yellow_cards between 0 and 2),
  red_cards smallint not null default 0 check (red_cards between 0 and 1),

  -- Goalkeeper-ready fields are stored from the start so v2.2.x will not need
  -- a destructive schema redesign when goalkeeper statistics are enabled.
  goals_conceded smallint not null default 0 check (goals_conceded between 0 and 30),
  saves smallint not null default 0 check (saves between 0 and 50),
  clean_sheet boolean not null default false,

  notes text,
  created_by uuid references auth.users(id) on delete set null,
  updated_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),

  constraint player_match_stats_match_player_unique unique (match_id, player_id)
);

create index if not exists player_match_stats_player_season_idx
  on public.player_match_stats (player_id, season_id, competition_id);
create index if not exists player_match_stats_match_idx
  on public.player_match_stats (match_id);
create index if not exists player_match_stats_season_competition_idx
  on public.player_match_stats (season_id, competition_id);

create table if not exists public.match_statistics_status (
  match_id bigint primary key
    references public.matches(id) on delete cascade,
  status text not null default 'draft'
    check (status in ('draft', 'complete')),
  completed_at timestamptz,
  completed_by uuid references auth.users(id) on delete set null,
  updated_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- Keep season / competition / club-team context in every row consistent with the match.
create or replace function public.sync_player_match_stat_context()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  v_competition_id bigint;
  v_season_id bigint;
  v_home_team_id bigint;
  v_away_team_id bigint;
  v_home_is_club boolean;
  v_away_is_club boolean;
begin
  select
    m.competition_id,
    c.season_id,
    m.home_team_id,
    m.away_team_id,
    coalesce(ht.is_club, false),
    coalesce(at.is_club, false)
  into
    v_competition_id,
    v_season_id,
    v_home_team_id,
    v_away_team_id,
    v_home_is_club,
    v_away_is_club
  from public.matches m
  left join public.competitions c on c.id = m.competition_id
  left join public.teams ht on ht.id = m.home_team_id
  left join public.teams at on at.id = m.away_team_id
  where m.id = new.match_id;

  if v_home_team_id is null then
    raise exception 'Match % does not exist', new.match_id;
  end if;

  new.competition_id := v_competition_id;
  new.season_id := v_season_id;

  if v_home_is_club then
    new.team_id := v_home_team_id;
  elsif v_away_is_club then
    new.team_id := v_away_team_id;
  elsif new.team_id is null then
    new.team_id := v_home_team_id;
  end if;

  new.updated_at := now();
  return new;
end;
$$;

drop trigger if exists player_match_stats_sync_context on public.player_match_stats;
create trigger player_match_stats_sync_context
before insert or update of match_id on public.player_match_stats
for each row execute function public.sync_player_match_stat_context();

-- If a match is moved to another tournament, refresh already entered stats context.
create or replace function public.refresh_match_stats_context()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if new.competition_id is distinct from old.competition_id
     or new.home_team_id is distinct from old.home_team_id
     or new.away_team_id is distinct from old.away_team_id then
    update public.player_match_stats
      set match_id = new.id
      where match_id = new.id;
  end if;
  return new;
end;
$$;

drop trigger if exists matches_refresh_player_stats_context on public.matches;
create trigger matches_refresh_player_stats_context
after update of competition_id, home_team_id, away_team_id on public.matches
for each row execute function public.refresh_match_stats_context();

-- Generic updated_at triggers already exist in the project.
drop trigger if exists seasons_set_updated_at on public.seasons;
create trigger seasons_set_updated_at
before update on public.seasons
for each row execute function public.set_generic_updated_at();

drop trigger if exists match_statistics_status_set_updated_at on public.match_statistics_status;
create trigger match_statistics_status_set_updated_at
before update on public.match_statistics_status
for each row execute function public.set_generic_updated_at();

-- Aggregation source for player pages / leaderboards in the next v2.2 releases.
create or replace view public.player_season_statistics
with (security_invoker = true)
as
select
  pms.player_id,
  pms.season_id,
  pms.competition_id,
  count(*)::integer as appearances,
  count(*) filter (where pms.appearance = 'starter')::integer as starts,
  count(*) filter (where pms.appearance = 'substitute')::integer as substitute_appearances,
  coalesce(sum(pms.minutes_played), 0)::integer as minutes_played,
  coalesce(sum(pms.goals), 0)::integer as goals,
  coalesce(sum(pms.assists), 0)::integer as assists,
  coalesce(sum(pms.own_goals), 0)::integer as own_goals,
  coalesce(sum(pms.penalties_scored), 0)::integer as penalties_scored,
  coalesce(sum(pms.penalties_missed), 0)::integer as penalties_missed,
  coalesce(sum(pms.yellow_cards), 0)::integer as yellow_cards,
  coalesce(sum(pms.red_cards), 0)::integer as red_cards,
  coalesce(sum(pms.goals_conceded), 0)::integer as goals_conceded,
  coalesce(sum(pms.saves), 0)::integer as saves,
  count(*) filter (where pms.clean_sheet)::integer as clean_sheets
from public.player_match_stats pms
join public.matches m on m.id = pms.match_id
where m.status = 'finished'
group by pms.player_id, pms.season_id, pms.competition_id;

alter table public.seasons enable row level security;
alter table public.player_match_stats enable row level security;
alter table public.match_statistics_status enable row level security;

grant select on table public.seasons, public.player_match_stats to anon, authenticated;
grant select on table public.player_season_statistics to anon, authenticated;
grant insert, update, delete on table public.seasons, public.player_match_stats, public.match_statistics_status to authenticated;
grant select on table public.match_statistics_status to authenticated;

grant usage, select on sequence public.seasons_id_seq to authenticated;
grant usage, select on sequence public.player_match_stats_id_seq to authenticated;

-- Seasons: public active read; editors manage.
drop policy if exists "Public can read active seasons" on public.seasons;
create policy "Public can read active seasons"
on public.seasons for select
to public
using (is_active = true);

drop policy if exists "Editors can read all seasons" on public.seasons;
create policy "Editors can read all seasons"
on public.seasons for select
to authenticated
using (public.is_editor_or_admin());

drop policy if exists "Editors create seasons" on public.seasons;
create policy "Editors create seasons"
on public.seasons for insert
to authenticated
with check (public.is_editor_or_admin());

drop policy if exists "Editors update seasons" on public.seasons;
create policy "Editors update seasons"
on public.seasons for update
to authenticated
using (public.is_editor_or_admin())
with check (public.is_editor_or_admin());

drop policy if exists "Admins delete seasons" on public.seasons;
create policy "Admins delete seasons"
on public.seasons for delete
to authenticated
using (public.current_user_role() = 'admin'::public.user_role);

-- Match player statistics: public read; editors write; only admin deletes rows.
drop policy if exists "Public can read player match stats" on public.player_match_stats;
create policy "Public can read player match stats"
on public.player_match_stats for select
to public
using (true);

drop policy if exists "Editors create player match stats" on public.player_match_stats;
create policy "Editors create player match stats"
on public.player_match_stats for insert
to authenticated
with check (public.is_editor_or_admin());

drop policy if exists "Editors update player match stats" on public.player_match_stats;
create policy "Editors update player match stats"
on public.player_match_stats for update
to authenticated
using (public.is_editor_or_admin())
with check (public.is_editor_or_admin());

drop policy if exists "Admins delete player match stats" on public.player_match_stats;
create policy "Admins delete player match stats"
on public.player_match_stats for delete
to authenticated
using (public.current_user_role() = 'admin'::public.user_role);

-- Completion status is an editorial workflow detail, not public data.
drop policy if exists "Editors read match statistics status" on public.match_statistics_status;
create policy "Editors read match statistics status"
on public.match_statistics_status for select
to authenticated
using (public.is_editor_or_admin());

drop policy if exists "Editors create match statistics status" on public.match_statistics_status;
create policy "Editors create match statistics status"
on public.match_statistics_status for insert
to authenticated
with check (public.is_editor_or_admin());

drop policy if exists "Editors update match statistics status" on public.match_statistics_status;
create policy "Editors update match statistics status"
on public.match_statistics_status for update
to authenticated
using (public.is_editor_or_admin())
with check (public.is_editor_or_admin());

drop policy if exists "Admins delete match statistics status" on public.match_statistics_status;
create policy "Admins delete match statistics status"
on public.match_statistics_status for delete
to authenticated
using (public.current_user_role() = 'admin'::public.user_role);


-- Refresh PostgREST schema cache after adding the new tables/view.
notify pgrst, 'reload schema';
