-- FC EDINEȚ v2.3.0 — Match statistics foundation / Match Center
-- Run AFTER 040_statistics_final_qa.sql.
-- Safe to run more than once.
-- Creates the durable data model for the v2.3 match-report branch:
-- report metadata, two team-stat rows per match, match events and an editor progress view.

create table if not exists public.match_reports (
  match_id bigint primary key
    references public.matches(id) on delete cascade,
  status text not null default 'draft'
    check (status in ('draft', 'complete')),
  referee text,
  attendance integer
    check (attendance is null or attendance between 0 and 200000),
  weather text,
  pitch_condition text,
  summary text,
  man_of_match_player_id uuid
    references public.players(id) on delete set null,
  completed_at timestamptz,
  completed_by uuid references auth.users(id) on delete set null,
  created_by uuid references auth.users(id) on delete set null,
  updated_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.match_team_statistics (
  id bigint generated by default as identity primary key,
  match_id bigint not null
    references public.matches(id) on delete cascade,
  team_id bigint not null
    references public.teams(id) on delete restrict,
  side text not null
    check (side in ('home', 'away')),

  -- Nullable by design: NULL means "not entered yet", while 0 is a real value.
  possession_percent numeric(5,2)
    check (possession_percent is null or possession_percent between 0 and 100),
  shots smallint
    check (shots is null or shots between 0 and 100),
  shots_on_target smallint
    check (shots_on_target is null or shots_on_target between 0 and 100),
  corners smallint
    check (corners is null or corners between 0 and 60),
  fouls smallint
    check (fouls is null or fouls between 0 and 80),
  offsides smallint
    check (offsides is null or offsides between 0 and 40),
  yellow_cards smallint
    check (yellow_cards is null or yellow_cards between 0 and 20),
  red_cards smallint
    check (red_cards is null or red_cards between 0 and 10),
  passes_attempted smallint
    check (passes_attempted is null or passes_attempted between 0 and 1500),
  passes_completed smallint
    check (passes_completed is null or passes_completed between 0 and 1500),
  saves smallint
    check (saves is null or saves between 0 and 100),
  expected_goals numeric(5,2)
    check (expected_goals is null or expected_goals between 0 and 30),
  notes text,

  created_by uuid references auth.users(id) on delete set null,
  updated_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),

  constraint match_team_statistics_match_side_unique unique (match_id, side),
  constraint match_team_statistics_shots_target_lte_shots_check check (
    shots is null or shots_on_target is null or shots_on_target <= shots
  ),
  constraint match_team_statistics_passes_check check (
    passes_attempted is null or passes_completed is null or passes_completed <= passes_attempted
  )
);

create table if not exists public.match_events (
  id bigint generated by default as identity primary key,
  match_id bigint not null
    references public.matches(id) on delete cascade,
  team_id bigint
    references public.teams(id) on delete set null,
  player_id uuid
    references public.players(id) on delete set null,
  player_name text,
  related_player_id uuid
    references public.players(id) on delete set null,
  related_player_name text,
  event_type text not null
    check (event_type in (
      'goal', 'own_goal', 'penalty_goal', 'penalty_miss',
      'yellow_card', 'red_card', 'substitution', 'var',
      'injury', 'other'
    )),
  minute smallint not null default 0
    check (minute between 0 and 130),
  stoppage_minute smallint not null default 0
    check (stoppage_minute between 0 and 30),
  description text,
  sort_order integer not null default 0,
  created_by uuid references auth.users(id) on delete set null,
  updated_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists match_team_statistics_match_idx
  on public.match_team_statistics (match_id, side);
create index if not exists match_events_match_minute_idx
  on public.match_events (match_id, minute, stoppage_minute, sort_order, id);
create index if not exists match_events_player_idx
  on public.match_events (player_id, match_id);

-- Reuse the generic timestamp trigger already introduced in the project.
drop trigger if exists match_reports_set_updated_at on public.match_reports;
create trigger match_reports_set_updated_at
before update on public.match_reports
for each row execute function public.set_generic_updated_at();

drop trigger if exists match_team_statistics_set_updated_at on public.match_team_statistics;
create trigger match_team_statistics_set_updated_at
before update on public.match_team_statistics
for each row execute function public.set_generic_updated_at();

drop trigger if exists match_events_set_updated_at on public.match_events;
create trigger match_events_set_updated_at
before update on public.match_events
for each row execute function public.set_generic_updated_at();

-- The side is the source of truth. The team id is always synchronized with
-- the current home/away teams of the match so a later match edit cannot leave
-- stale team-stat rows behind.
create or replace function public.sync_match_team_stat_context()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  v_home_team_id bigint;
  v_away_team_id bigint;
begin
  select home_team_id, away_team_id
  into v_home_team_id, v_away_team_id
  from public.matches
  where id = new.match_id;

  if v_home_team_id is null or v_away_team_id is null then
    raise exception 'Match % does not exist', new.match_id;
  end if;

  if new.side = 'home' then
    new.team_id := v_home_team_id;
  else
    new.team_id := v_away_team_id;
  end if;

  return new;
end;
$$;

drop trigger if exists match_team_statistics_sync_context on public.match_team_statistics;
create trigger match_team_statistics_sync_context
before insert or update of match_id, side, team_id on public.match_team_statistics
for each row execute function public.sync_match_team_stat_context();

-- Every match owns exactly two foundation rows: home and away. They are
-- created automatically for old matches and for every new match.
create or replace function public.ensure_match_team_stat_rows()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.match_team_statistics (match_id, team_id, side)
  values (new.id, new.home_team_id, 'home')
  on conflict (match_id, side) do update
    set team_id = excluded.team_id;

  insert into public.match_team_statistics (match_id, team_id, side)
  values (new.id, new.away_team_id, 'away')
  on conflict (match_id, side) do update
    set team_id = excluded.team_id;

  return new;
end;
$$;

drop trigger if exists matches_ensure_team_stat_rows on public.matches;
create trigger matches_ensure_team_stat_rows
after insert or update of home_team_id, away_team_id on public.matches
for each row execute function public.ensure_match_team_stat_rows();

insert into public.match_team_statistics (match_id, team_id, side)
select id, home_team_id, 'home'
from public.matches
on conflict (match_id, side) do update
set team_id = excluded.team_id;

insert into public.match_team_statistics (match_id, team_id, side)
select id, away_team_id, 'away'
from public.matches
on conflict (match_id, side) do update
set team_id = excluded.team_id;

-- Row level security: v2.3.0 is an editor-only foundation. Public policies
-- will be added later when the public match page is introduced.
alter table public.match_reports enable row level security;
alter table public.match_team_statistics enable row level security;
alter table public.match_events enable row level security;

grant select, insert, update, delete on table
  public.match_reports,
  public.match_team_statistics,
  public.match_events
to authenticated;

grant usage, select on sequence public.match_team_statistics_id_seq to authenticated;
grant usage, select on sequence public.match_events_id_seq to authenticated;

drop policy if exists "Editors manage match reports" on public.match_reports;
create policy "Editors manage match reports"
on public.match_reports for all
to authenticated
using (public.is_editor_or_admin())
with check (public.is_editor_or_admin());

drop policy if exists "Editors manage match team statistics" on public.match_team_statistics;
create policy "Editors manage match team statistics"
on public.match_team_statistics for all
to authenticated
using (public.is_editor_or_admin())
with check (public.is_editor_or_admin());

drop policy if exists "Editors manage match events" on public.match_events;
create policy "Editors manage match events"
on public.match_events for all
to authenticated
using (public.is_editor_or_admin())
with check (public.is_editor_or_admin());

-- One compact progress source for the Match Center. This deliberately exposes
-- only workflow/count information, not detailed draft values.
drop view if exists public.match_center_progress;
create view public.match_center_progress
with (security_invoker = true)
as
select
  m.id as match_id,
  coalesce(mr.status, 'empty')::text as report_status,
  coalesce(mss.status, 'empty')::text as player_stats_status,
  count(distinct mts.id)::integer as team_rows,
  count(distinct mts.id) filter (
    where mts.possession_percent is not null
       or mts.shots is not null
       or mts.shots_on_target is not null
       or mts.corners is not null
       or mts.fouls is not null
       or mts.offsides is not null
       or mts.passes_attempted is not null
       or mts.expected_goals is not null
  )::integer as team_stats_filled,
  count(distinct me.id)::integer as events_count,
  (
    mr.referee is not null
    or mr.attendance is not null
    or mr.weather is not null
    or mr.pitch_condition is not null
    or mr.summary is not null
    or mr.man_of_match_player_id is not null
  ) as report_has_metadata
from public.matches m
left join public.match_reports mr on mr.match_id = m.id
left join public.match_statistics_status mss on mss.match_id = m.id
left join public.match_team_statistics mts on mts.match_id = m.id
left join public.match_events me on me.match_id = m.id
where public.is_editor_or_admin()
group by m.id, mr.status, mss.status, mr.referee, mr.attendance,
         mr.weather, mr.pitch_condition, mr.summary, mr.man_of_match_player_id;

grant select on table public.match_center_progress to authenticated;

notify pgrst, 'reload schema';
