-- FC EDINEȚ v2.3.7 — Match lineups and substitution-ready roster
-- Run AFTER 041_match_statistics_foundation.sql.
-- Safe to run more than once.

create table if not exists public.match_lineup_settings (
  id bigint generated by default as identity primary key,
  match_id bigint not null references public.matches(id) on delete cascade,
  team_id bigint not null references public.teams(id) on delete cascade,
  side text not null check (side in ('home','away')),
  formation text,
  coach_name text,
  created_by uuid references auth.users(id) on delete set null,
  updated_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint match_lineup_settings_match_side_unique unique (match_id, side)
);

create table if not exists public.match_lineup_entries (
  id bigint generated by default as identity primary key,
  match_id bigint not null references public.matches(id) on delete cascade,
  team_id bigint not null references public.teams(id) on delete cascade,
  side text not null check (side in ('home','away')),
  lineup_role text not null check (lineup_role in ('starter','substitute')),
  slot_number smallint not null check (slot_number between 1 and 30),
  player_id uuid references public.players(id) on delete set null,
  player_name text,
  shirt_number smallint check (shirt_number is null or shirt_number between 0 and 99),
  position text check (
    position is null or position in ('goalkeeper','defender','midfielder','forward')
  ),
  is_captain boolean not null default false,
  sort_order integer not null default 0,
  created_by uuid references auth.users(id) on delete set null,
  updated_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint match_lineup_entries_slot_unique unique (match_id, side, lineup_role, slot_number),
  constraint match_lineup_entries_player_or_name_check check (
    player_id is not null or nullif(btrim(player_name), '') is not null
  )
);

create index if not exists match_lineup_entries_match_side_idx
  on public.match_lineup_entries (match_id, side, lineup_role, slot_number);
create index if not exists match_lineup_entries_player_idx
  on public.match_lineup_entries (player_id, match_id);

-- Keep timestamps fresh.
drop trigger if exists match_lineup_settings_set_updated_at on public.match_lineup_settings;
create trigger match_lineup_settings_set_updated_at
before update on public.match_lineup_settings
for each row execute function public.set_generic_updated_at();

drop trigger if exists match_lineup_entries_set_updated_at on public.match_lineup_entries;
create trigger match_lineup_entries_set_updated_at
before update on public.match_lineup_entries
for each row execute function public.set_generic_updated_at();

-- The side is the source of truth. team_id always follows the current match teams.
create or replace function public.sync_match_lineup_context()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  v_home_team_id bigint;
  v_away_team_id bigint;
begin
  select home_team_id, away_team_id
  into v_home_team_id, v_away_team_id
  from public.matches
  where id = new.match_id;

  if v_home_team_id is null or v_away_team_id is null then
    raise exception 'Match % does not exist', new.match_id;
  end if;

  if new.side = 'home' then
    new.team_id := v_home_team_id;
  else
    new.team_id := v_away_team_id;
  end if;

  return new;
end;
$$;

drop trigger if exists match_lineup_settings_sync_context on public.match_lineup_settings;
create trigger match_lineup_settings_sync_context
before insert or update of match_id, side, team_id on public.match_lineup_settings
for each row execute function public.sync_match_lineup_context();

drop trigger if exists match_lineup_entries_sync_context on public.match_lineup_entries;
create trigger match_lineup_entries_sync_context
before insert or update of match_id, side, team_id on public.match_lineup_entries
for each row execute function public.sync_match_lineup_context();

-- One captain maximum per side. This is partial so rows without a captain stay unrestricted.
create unique index if not exists match_lineup_entries_one_captain_idx
  on public.match_lineup_entries (match_id, side)
  where is_captain = true;

alter table public.match_lineup_settings enable row level security;
alter table public.match_lineup_entries enable row level security;

grant select, insert, update, delete on table
  public.match_lineup_settings,
  public.match_lineup_entries
to authenticated;

grant usage, select on sequence public.match_lineup_settings_id_seq to authenticated;
grant usage, select on sequence public.match_lineup_entries_id_seq to authenticated;

drop policy if exists "Editors manage match lineup settings" on public.match_lineup_settings;
create policy "Editors manage match lineup settings"
on public.match_lineup_settings for all
to authenticated
using (public.is_editor_or_admin())
with check (public.is_editor_or_admin());

drop policy if exists "Editors manage match lineup entries" on public.match_lineup_entries;
create policy "Editors manage match lineup entries"
on public.match_lineup_entries for all
to authenticated
using (public.is_editor_or_admin())
with check (public.is_editor_or_admin());

-- Match Center progress now also knows how complete the lineups are.
drop view if exists public.match_center_progress;
create view public.match_center_progress
with (security_invoker = true)
as
select
  m.id as match_id,
  coalesce(mr.status, 'empty')::text as report_status,
  coalesce(mss.status, 'empty')::text as player_stats_status,
  count(distinct mts.id)::integer as team_rows,
  count(distinct mts.id) filter (
    where mts.possession_percent is not null
       or mts.shots is not null
       or mts.shots_on_target is not null
       or mts.corners is not null
       or mts.fouls is not null
       or mts.offsides is not null
       or mts.passes_attempted is not null
       or mts.expected_goals is not null
  )::integer as team_stats_filled,
  count(distinct me.id)::integer as events_count,
  count(distinct mle.id) filter (where mle.side = 'home' and mle.lineup_role = 'starter')::integer as home_starters,
  count(distinct mle.id) filter (where mle.side = 'away' and mle.lineup_role = 'starter')::integer as away_starters,
  count(distinct mle.id) filter (where mle.side = 'home' and mle.lineup_role = 'substitute')::integer as home_substitutes,
  count(distinct mle.id) filter (where mle.side = 'away' and mle.lineup_role = 'substitute')::integer as away_substitutes,
  (
    mr.referee is not null
    or mr.attendance is not null
    or mr.weather is not null
    or mr.pitch_condition is not null
    or mr.summary is not null
    or mr.man_of_match_player_id is not null
  ) as report_has_metadata
from public.matches m
left join public.match_reports mr on mr.match_id = m.id
left join public.match_statistics_status mss on mss.match_id = m.id
left join public.match_team_statistics mts on mts.match_id = m.id
left join public.match_events me on me.match_id = m.id
left join public.match_lineup_entries mle on mle.match_id = m.id
where public.is_editor_or_admin()
group by m.id, mr.status, mss.status, mr.referee, mr.attendance,
         mr.weather, mr.pitch_condition, mr.summary, mr.man_of_match_player_id;

grant select on table public.match_center_progress to authenticated;

notify pgrst, 'reload schema';
