import Link from "next/link";
import { createClient } from "@/lib/supabase/server";
import type { Partner, PartnerLevel } from "@/lib/types";
import { getLocale } from "@/lib/locale";
import { localized, partnerLevelLabelsI18n, publicText, type Locale } from "@/lib/i18n";
export const dynamic="force-dynamic";
const levelOrder:PartnerLevel[]=["main","official","technical","supporter"];
export default async function PartnersPage(){const locale=await getLocale();const text=publicText[locale].partners;const supabase=await createClient();const {data}=await supabase.from("partners").select("*").eq("is_active",true).order("display_order").order("name");const partners=(data??[]) as Partner[];return <main className="partnersPage"><section className="pageHero partnersHero"><div className="container"><p className="eyebrow">{text.eyebrow}</p><h1>{text.title}</h1><p>{text.description}</p></div></section><section className="section"><div className="container">{!partners.length?<div className="adminEmpty">{text.empty}</div>:<div className="partnersPublicGroups">{levelOrder.map(level=>{const items=partners.filter(p=>p.partner_level===level);if(!items.length)return null;return <section className="partnerPublicGroup" key={level}><div className="sectionHeading"><div><p className="eyebrow blue">{text.cooperation}</p><h2>{partnerLevelLabelsI18n[locale][level]}</h2></div></div><div className="partnerPublicGrid">{items.map(p=><PartnerCard partner={p} locale={locale} key={p.id}/>)}</div></section>})}</div>}<div className="partnersContactBox"><div><p className="eyebrow blue">{text.cooperation}</p><h2>{text.become}</h2><p>{text.contact}</p></div><Link href="/club" className="primaryButton">{text.clubContacts}</Link></div></div></section></main>}
function PartnerCard({partner,locale}:{partner:Partner;locale:Locale}){const text=publicText[locale].partners;const content=<><div className="partnerPublicLogo"><img src={partner.logo_url} alt={partner.name}/></div><div className="partnerPublicText"><strong>{partner.name}</strong>{localized(partner.description,partner.description_ro,locale)&&<p>{localized(partner.description,partner.description_ro,locale)}</p>}{partner.website_url&&<span>{text.openSite}</span>}</div></>;return partner.website_url?<a className="partnerPublicCard" href={partner.website_url} target="_blank" rel="noopener noreferrer">{content}</a>:<article className="partnerPublicCard">{content}</article>}
